owner: blryface
repo: uptime

sites:
  - name: Notessential
    url: https://notessential.blurry.gay
  - name: CRSS Website
    url: https://crss.cc
  - name: Pridecraft Website
    url: https://pridecraft.gay
  - name: CRSS Server (Proxy)
    check: "tcp-ping"
    url: 132.145.233.75
    port: 25565
    icon: https://crss.cc/favicon.ico
  - name: CRSS Server (SMP)
    check: "tcp-ping"
    url: 132.145.233.75
    port: 25565
    icon: https://crss.cc/favicon.ico
  - name: CRSS 3 Server
    check: "tcp-ping"
    url: 141.147.29.5
    port: 42069
    icon: https://crss.cc/favicon.ico

status-website:
  cname: status.blurry.gay
  logoUrl: https://blurry.gay/favicon.png
  name: Status
  introTitle: "Status page for my servers and services."
  introMessage: This is the status page for all my servers and services. There's not much here now, but the list may increase as I realize I need to add a status page for some of my projects, and as I make more and more Minecraft servers.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://blurry.gay
    - title: Notessential
      href: https://notessential.blurry.gay

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
